config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  root "games#index"
  resources :games, only: [:index, :new, :create, :show, :update] do
    resources :gameplays, only: [:update]
  end
  resources :pieces, only: [:update]
  resources :gameplays, only: [:index, :create]
end

app/models/game.rb
class Game < ApplicationRecord
  after_create :new_board!

  has_many :players, through: :gameplays
  has_many :pieces
  has_many :gameplays

  def board
    board =[]
    8.times do
      board <<  Array.new(8)
    end
    pieces.each do |piece|
      unless piece.x == 8
        board[piece.y][piece.x] = piece
      end
    end
    board
  end

  def turn?
    if turn % 2 == 0
      true
    else
      false
    end
  end

  def piece_at(x, y)
    pieces.where(x: x, y: y).last
  end

  def piece_at?(x, y)
    piece_at(x, y) ? true : false
  end

  def check?(color)
    king = king(color)
    pieces_inplay(!color).each do |pc|
      if pc.move_capable?(king.x, king.y)
        unless pc.blocked?(king.x, king.y)
          @assassin = pc
          return true
        end
      end
    end
    false
  end

  def checkmate?(color)
    unless check?(color)
      return false
    end
    king = king(color)
    pieces_inplay(color).each do |pc|
      if pc.move_capable?(@assassin.x, @assassin.y)
        unless pc.blocked?(@assassin.x, @assassin.y)
          # if !check_causing_move
          return false
        end
      elsif @assassin.sliding && !@assassin.paths(king.x, king.y).empty?
        @assassin.paths(king.x, king.y).each do |sq|
          if pc.move_capable?(sq[0], sq[1])
            unless pc.blocked?(sq[0], sq[1])
              # if !check_causing_move
              return false
            end
          end
        end
      elsif king.escape?
        return false
      end
    end
    true
  end

  def pieces_inplay(color)
    pieces.where(color: color).where.not(state: "off")
  end

  def king(color)
    pieces.find_by(type: 'King', color: color)
  end

private

  def new_board!
    board =[]
    8.times do
      board <<  Array.new(8)
    end
    board[0][0] = Rook.create(game_id: self.id, color: false, y: 0, x: 0, sliding: true, state: "on")
    board[0][7] = Rook.create(game_id: self.id, color: false, y: 0, x: 7, sliding: true, state: "on")
    board[0][1] = Knight.create(game_id: self.id, color: false, y: 0, x: 1, sliding: false, state: "on")
    board[0][6] = Knight.create(game_id: self.id, color: false, y: 0, x: 6, sliding: false, state: "on")
    board[0][2] = Bishop.create(game_id: self.id, color: false, y: 0, x: 2, sliding: true, state: "on")
    board[0][5] = Bishop.create(game_id: self.id, color: false, y: 0, x: 5, sliding: true, state: "on")
    board[0][3] = Queen.create(game_id: self.id, color: false, y: 0, x: 3, sliding: true, state: "on")
    board[0][4] = King.create(game_id: self.id, color: false, y: 0, x: 4, sliding: false, state: "on")
    board[7][0] = Rook.create(game_id: self.id, color: true, y: 7, x: 0, sliding: true, state: "on")
    board[7][7] = Rook.create(game_id: self.id, color: true, y: 7, x: 7, sliding: true, state: "on")
    board[7][1] = Knight.create(game_id: self.id, color: true, y: 7, x: 1, sliding: false, state: "on")
    board[7][6] = Knight.create(game_id: self.id, color: true, y: 7, x: 6, sliding: false, state: "on")
    board[7][2] = Bishop.create(game_id: self.id, color: true, y: 7, x: 2, sliding: true, state: "on")
    board[7][5] = Bishop.create(game_id: self.id, color: true, y: 7, x: 5, sliding: true, state: "on")
    board[7][3] = Queen.create(game_id: self.id, color: true, y: 7, x: 3, sliding: true, state: "on")
    board[7][4] = King.create(game_id: self.id, color: true, y: 7, x: 4, sliding: false, state: "on")
    (0..7).each do |col|
      board[1][col] = Pawn.create(game_id: self.id, color: false, y: 1, x: col, sliding: false, state: "on")
      board[6][col] = Pawn.create(game_id: self.id, color: true, y: 6, x: col, sliding: false, state: "on")
    end
    board
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper
  def index
    @player = current_player
    @games = Game.joins(gameplays: :player).where(gameplays: { player_id: @player })
  end

  def show
    @player = current_player
    @game = Game.find(params[:id])
    figuratize(@game)
    fill_graves(@game)
    player_color(@game)
  end

  def new
    @game = Game.new
    @gameplay = Gameplay.new
  end

  def create
    @player = current_player
    @game = Game.new(game_params)
    if @game.save
      Gameplay.create(game_id: @game.id, player_id: current_player.id, color: false)
      redirect_to game_path(@game)
    else
      flash[:errors] = @game.errors.full_messages.join(". ")
      render :new
    end
  end

  def update
    @game = Game.find(game_params)
    if @game.update
      redirect_to game_path(@game)
    else
      flash[:errors] = @game.errors.full_messages.join(". ")
    end
  end

  private

  def game_params
    params.require(:game).permit(:title, :state, :turn, :result, :winning_player_id, :draw_offerer_id)
  end

end

app/helpers/games_helper.rb
module GamesHelper
  FIG_COLORS = Hash[true, "b", false, "w"]
  FIG_TYPES = Hash["Bishop", "b", "King", "k", "Knight", "n", "Pawn", "p", "Queen", "q", "Rook", "r"]

  def figure
    "#{FIG_COLORS[self.color]}#{FIG_TYPES[self.type]}.svg"
  end

  def figuratize(game)
    board = game.board
    gon.board = board
    piece_figs = []
    8.times do
      piece_figs <<  Array.new(8)
    end
    board.each_with_index do |row, i|
      row.each_with_index do |piece, col|
        if piece
          piece_figs[i][col] = ["#{piece.color}", piece.figure]
        end
      end
    end
    gon.figs = piece_figs
  end

  def fill_graves(game)
    b_dead_figs = []
    w_dead_figs = []
    b_dead_pieces = Piece.where(game: game, x: 8, color: true).order(updated_at: :asc)
    w_dead_pieces = Piece.where(game: game, x: 8, color: false).order(updated_at: :asc)
    b_dead_pieces.each do |piece|
      b_dead_figs << piece.figure
    end
    w_dead_pieces.each do |piece|
      w_dead_figs << piece.figure
    end
    gon.b_graves = b_dead_pieces
    gon.w_graves = w_dead_pieces
    gon.b_dead_figs = b_dead_figs
    gon.w_dead_figs = w_dead_figs
  end

  def player_color(game)
    gon.player_color = game.gameplays.where(player_id: current_player.id)[0].color
  end

  def paths(file, rank)
    diagonal_path(file, rank) + square_path(file, rank)
  end

  def diagonal_path(file, rank)
    xpos = x
    ypos = y
    steps = []
    file, rank = file.to_i, rank.to_i

    unless file == xpos || rank == ypos
      delta_x = file > xpos ? 1 : -1
      delta_y = rank > ypos ? 1 : -1

      xpos += delta_x
      ypos += delta_y

      while (file - xpos).abs > 0 && (rank - ypos).abs > 0
        steps << [xpos, ypos]
        xpos += delta_x
        ypos += delta_y
      end
    end
    steps
  end

  def square_path(file, rank)
    xpos = x
    ypos = y
    steps = []
    file, rank = file.to_i, rank.to_i

    if rank == ypos
      delta_x = file > xpos ? 1 : -1
      xpos += delta_x
      while (file - xpos).abs > 0
        steps << [xpos, ypos]
        xpos += delta_x
      end
    elsif file == xpos
      delta_y = rank > ypos ? 1 : -1
      ypos += delta_y
      while (rank - ypos).abs > 0
        steps << [xpos, ypos]
        ypos += delta_y
      end
    end
    steps
  end
end

app/views/games/index.html.erb
<div id="index">
  <h1 id="gamesheader">
    <% if player_signed_in? %>
      My Games
    <% else %>
      Welcome!
    <% end %>
  </h1>
  <div class="inline" id="gamesbody">
    <% if player_signed_in? %>
      <div>
        <ul>
          <% @games.each do |game| %>
            <li>
              <% unless game.title %>
                <%= link_to "Game #{game.id}", game_path %>
              <% end %>
              <%= link_to "#{game.title}", game_path(game.id) %>
            </li>
          <% end %>
        </ul>
      </div>
      <div>
        <%= link_to "Start New Game", new_game_path %>
      </div>
      <div class="inline" id="gamesjoin">
        <%= link_to "Join New Game", gameplays_path %>
      </div>
    <% else %>
      <%= link_to "Sign up to play chess", new_player_registration_path %>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div id="new">
  <h1>Start New Game Here</h1>
  <div id="newform">
    <%= simple_form_for @game do |f| %>
      <%= f.label :title, "Name Your Game:" %>
      <%= f.text_field :title %>
      <%= f.submit "Begin!" %>
    <% end %>
  </div>
  </br>
</div>

app/views/games/show.html.erb
<div id="show">
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "chess_board.js" %>
  <%= javascript_include_tag "gameplay.js" %>
<% end %>
<h5><%= @game.title %></h5>
<div id="cbwithgys">
  <ul id="cbgylist">
    <li class="inline">
      <div class="gylist" id="blackgy">
        <table class="gy" id="bgrave"><td data-x='8' data-y="8" data-color="true"></td></table>
      </div>
    </li>
    <li class="inline"><table id="chessboard" data-turn='TODO:turn?'></table></li>
    <li class="inline">
      <div class="gylist" id="whitegy">
        <table class="gy" id="wgrave"><td data-x='8' data-y="8" data-color="false"></td></table>
      </div>
    </li>
  </ul>
</div>

<div>
<div>
</br>
</div>
</div>
<script>

  channel.bind('move_event', function(data) {
    var piece = data.piece;
    var fig = data.fig;
    var color = data.piece.color;
    var pieceimg = pieceImg(piece, fig, color);
    var origin = $("img[data-piece-id='" + piece.id +"']");
    if (piece.x == 8){
      var target = $("td[data-color='" + color + "']")
    } else {
      var target = $("td[data-y='" + piece.y +"'][data-x='" + piece.x + "']")
    };
    $("td.selected").removeClass('selected');
    target.append(pieceimg);
    origin.remove();
  });
</script>