config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  root "games#index"
  resources :games, only: [:index, :new, :create, :show, :update] do
    resources :gameplays, only: [:update]
  end
  resources :pieces, only: [:update]
  resources :gameplays, only: [:index, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Toy-Chess</title>
    <%= javascript_include_tag "//js.pusher.com/3.0/pusher.min.js" %>
    <%= Gon::Base.render_data({}) %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => false %>
    <script>
      var pusher = new Pusher('<%= ENV['PUSHER_KEY'] %>')
      var channelName = 'public-conversation';
      var channel = pusher.subscribe(channelName);
    </script>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">Toy-Chess</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
      <ul class="right">
        <% if player_signed_in? %>
          <li id="signed_in">Signed in as:</li><li id="signed_in"><strong><%= current_player.user_name %></strong></li>
          <li><strong><%= link_to 'Sign Out', destroy_player_session_path, method: :delete %></strong></li>
        <% else %>
          <li><strong><%= link_to 'Sign In', new_player_session_path %></strong></li>
          <li><strong><%= link_to 'Sign Up', new_player_registration_path %></strong></li>
        <% end %>
      </ul>
      
      <ul class="left">
        <li><a href="/">Home</a></li>
      </ul>
    </section>
  </nav>
    <div class="row">
      <% flash.each do |key, value| %>
        <div data-alert class="alert-box radius flash <%= key %>">
          <%= value %>
          <a href="/" class="close">&times;</a>
        </div>
      <% end %>
    </div>

    <%= yield %>
    <%= yield :javascript_includes %>

  </body>
</html>